### ISSUE TITLE
Not working for QB core 

### ISSUE THREAD

**Issue by MrHooliNoodle** [Force-Developing/force-sling#2]
I didn't mess with any code or anything other than the ones listed on the readme, but i get this error -
SCRIPT ERROR: @force-sling/client/main.lua:7: attempt to call a nil value (global 'IsPlayerLoaded')^7
![image](https://github.com/user-attachments/assets/c6682817-796e-4705-91f8-afe6dab18e6e)
![image](https://github.com/user-attachments/assets/1e49d4ef-6eec-41b1-bc9f-6e31eddba937)

**Comment by Force-Developing** [comment]
Does it find you're framework?

**Comment by MrHooliNoodle** [comment]
how would i know?
